version: "3.9"

services:
  app:
    build: ./app
    env_file: env
    # environment:
    #   - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
